### ISSUE TITLE
Ablecop 0.4.0, not compatible with Planter

### ISSUE THREAD

**Issue by rickyc** [ableco/ablecop#36]
Always getting issues with [planter](https://github.com/ableco/planter) /cc @blim8183. I'd imagine this would break fino as well.

```
Bundler could not find compatible versions for gem "octokit":
  In Gemfile:
    ablecop was resolved to 0.4.0, which depends on
      octokit (~> 4.6.2)

    planter was resolved to 0.1.2, which depends on
      octokit (~> 4.3.0)

    ablecop was resolved to 0.4.0, which depends on
      pronto (~> 0.8.2) was resolved to 0.8.2, which depends on
        octokit (>= 4.1.0, ~> 4.3)
```

**Comment by dennmart** [comment]
@rickyc Thanks for the report! I submitted [a pull request](https://github.com/ableco/planter/pull/6) in Planter to update the Octokit dependency in that gem so that it doesn't clash with AbleCop.

**Comment by dennmart** [comment]
The Octokit dependency was updated in Planter (https://github.com/ableco/planter/pull/5). Thanks @rickyc :tada:
