### ISSUE TITLE
Update Rubocop when the gem is updated to fix a bug 

### ISSUE THREAD

**Issue by rickyc** [ableco/ablecop#46]
The current version of Ablecop / Rubocop `0.48.1` throws an error telling us to parenthesize scopes.

Our Code
```rb
scope :foo, -> { order(:bar) }
``` 

Rubocop Expects (🐛)
```rb
scope :foo, (-> { order(:bar) })
``` 

https://github.com/bbatsov/rubocop/issues/4345

---

When Rubocop is updated to the next minor or patch release, we should update it so it doesn't throw this warning anymore on the linter.

**Comment by dennmart** [comment]
The RuboCop issue was fixed in https://github.com/bbatsov/rubocop/pull/4237, which was part of the 0.49.0 release. AbleCop 0.6.0 is now using RuboCop 0.49.1 so this is resolved.
