### ISSUE TITLE
Can we lessen the strictness of Style/GuardClause?

### ISSUE THREAD

**Issue by juliogarciag** [ableco/ablecop#47]
What do you think about lessening the strictness of the `Style/GuardClause` cop? Rubocop complains about this kind of code:

```ruby
if date && date > Time.zone.today.end_of_day
  errors.add(:date, "cannot be in the future")
end
```

This is the proposed rubocop solution: 

```ruby
return unless date.present? && date > Time.zone.today.end_of_day
errors.add(:date, "cannot be in the future")
```

I think it's not as easy to read as the initial idea. In fact, I find it counter-intuitive to the way somebody can mentally create the algorithm: It's more natural to think: `if there's a date and it's in the future, add an error`, instead of `return if it's false that the date is present and the date is in the future; then, add an error` (or even `return if the date is not present and the date is in the present or the past; then, add an error`).

I also thought of a one-liner solution:

```ruby
errors.add(:date, "cannot be in the future") if date && date > Time.zone.today.end_of_day
```

This one-liner wouldn't be possible if the field was named `investment_date` or `created_at` for example, because it would have had more than 100 characters in a single line. Also, this one-liner makes it difficult to add more statements. Anyway, I'm using it for a while.

I'm also missing the point of `Style/GuardClause`. I don't think a code full of short circuits is always good. I think it depends on the situation and the algorithm. What do you think?

**Comment by PuercoPop** [comment]
This is also a concern @ricardotk002 and myself have in the P- codebase. Ablecop is asking us to turn into guards things that are clearly not guards. Guards are used to check for preconditions, and as such they make sense at the start of the method. Flattening every one-armed if is not a good default strategy. I use `<foo> if/unless ..` when possible, but not every one-armed if has a single line in the body.

**Comment by ricardotk002** [comment]
I'm supportive of this idea, this rule is just too strict in my opinion. There are only a few cases where it is really useful and it is hard for an automated tool to determine when a conditional should be considered as a guard for the method. As Julio mentioned, this is leading us to sacrifice readability in favor of short-circuit evaluation, which, again, doesn't apply for all the cases.

I think that we, as developers, could do a better job writing and reviewing code that involves the use of guards.

**Comment by juliogarciag** [comment]
Closing it because of #48
